apiVersion: apps/v1
kind: Deployment
metadata:
  name: dof-exam-deploy-redis
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: redis-host
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: redis-host
    spec:
      containers:
      - name: redis-host
        image: schwarzkrieger/dof-exam-redis:%IMAGE-PLACEHOLDER%
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-host-svc
  labels:
    app: redis-host
spec:
  type: NodePort
  ports:
  - port: 6379
    nodePort: 6379
    protocol: TCP
  selector:
app: redis-host
