apiVersion: apps/v1
kind: Deployment
metadata:
  name: dof-exam-deploy-nginx
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: nginx-host
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nginx-host
    spec:
      containers:
      - name: nginx-host
        image: schwarzkrieger/dof-exam-nginx:%IMAGE-PLACEHOLDER%
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-host-svc
  labels:
    app: nginx-host
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 80
    protocol: TCP
  selector:
app: nginx-host
