apiVersion: apps/v1
kind: Deployment
metadata:
  name: dof-exam-deploy-php
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: php-host
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: php-host
    spec:
      containers:
      - name: php-host
        image: schwarzkrieger/dof-exam-php:%IMAGE-PLACEHOLDER%
        ports:
        - containerPort: 9000 
---
apiVersion: v1
kind: Service
metadata:
  name: php-host-svc
  labels:
    app: php-host
spec:
  type: NodePort
  ports:
  - port: 9000
    nodePort: 9000
    protocol: TCP
  selector:
app: php-host
