version: '3'

services:
  nginx-host:
    build: nginx/
#    COPY ./site/ /site/
#    RUN ls -la ./site/*
    ports:
    - "80:80"
    links:
    - php-host
    deploy: 
      mode: replicated
      replicas: 3
  php-host:
    build: php/
#    COPY ./site/ /site/
#    RUN ls -la ./site/*
    ports:
    - "9000:9000"
    links:
    - redis-host
  redis-host:
    image: redis:latest
